package com.jenkov.db.test.mapping;

import junit.framework.TestCase;
import com.jenkov.db.itf.mapping.IObjectMapping;
import com.jenkov.db.itf.mapping.IObjectMappingFactory;
import com.jenkov.db.impl.mapping.Key;
import com.jenkov.db.impl.mapping.AutoGeneratedColumnsMapper;
import com.jenkov.db.impl.mapping.ObjectMappingFactory;
import com.jenkov.db.test.objects.PersistentObject;

/**
 * @author Jakob Jenkov - Copyright 2005 Jenkov Development
 */
public class AutoGeneratedColumnsMapperTest extends TestCase{


    public void testModify_and_constructors() throws Exception {
        IObjectMappingFactory factory = new ObjectMappingFactory();
        IObjectMapping mapping = factory.createObjectMapping();
        mapping.addGetterMapping(factory.createGetterMapping(PersistentObject.class.getMethod("getId", null), "id", true));
        mapping.setPrimaryKey(new Key("id"));
        mapping.getGetterMapping("id").setAutoGenerated(false);
        assertFalse(mapping.getGetterMapping("id").isAutoGenerated());

        AutoGeneratedColumnsMapper mapper = new AutoGeneratedColumnsMapper(true);
        mapper.modify(null, mapping);
        assertTrue(mapping.getGetterMapping("id").isAutoGenerated());

        mapping.addGetterMapping(factory.createGetterMapping(PersistentObject.class.getMethod("getName", null), "name", true));
        mapping.getGetterMapping("id").setAutoGenerated(false);
        mapper = new AutoGeneratedColumnsMapper("name");
        mapper.modify(null, mapping);
        assertFalse(mapping.getGetterMapping("id").isAutoGenerated());
        assertTrue(mapping.getGetterMapping("name").isAutoGenerated());
        mapping.getGetterMapping("name").setAutoGenerated(false);

        mapping.addGetterMapping(factory.createGetterMapping(PersistentObject.class.getMethod("getName", null), "name", true));
        mapping.getGetterMapping("id").setAutoGenerated(false);
        mapper = new AutoGeneratedColumnsMapper(true, "name");
        mapper.modify(null, mapping);
        assertTrue(mapping.getGetterMapping("id").isAutoGenerated());
        assertTrue(mapping.getGetterMapping("name").isAutoGenerated());
        mapping.getGetterMapping("id").setAutoGenerated(false);
        mapping.getGetterMapping("name").setAutoGenerated(false);

        mapping.addGetterMapping(factory.createGetterMapping(PersistentObject.class.getMethod("getObject", null), "object", true));
        mapper = new AutoGeneratedColumnsMapper(new String[]{"name", "object"});
        mapper.modify(null, mapping);
        assertFalse(mapping.getGetterMapping("id").isAutoGenerated());
        assertTrue(mapping.getGetterMapping("name").isAutoGenerated());
        assertTrue(mapping.getGetterMapping("object").isAutoGenerated());
        mapping.getGetterMapping("name").setAutoGenerated(false);
        mapping.getGetterMapping("object").setAutoGenerated(false);

        mapping.addGetterMapping(factory.createGetterMapping(PersistentObject.class.getMethod("getObject", null), "object", true));
        mapper = new AutoGeneratedColumnsMapper(true, new String[]{"name", "object"});
        mapper.modify(null, mapping);
        assertTrue(mapping.getGetterMapping("id").isAutoGenerated());
        assertTrue(mapping.getGetterMapping("name").isAutoGenerated());
        assertTrue(mapping.getGetterMapping("object").isAutoGenerated());
        mapping.getGetterMapping("id").setAutoGenerated(false);
        mapping.getGetterMapping("name").setAutoGenerated(false);
        mapping.getGetterMapping("object").setAutoGenerated(false);
    }
}
