package com.jenkov.db.test.mapping;

import com.jenkov.db.itf.mapping.IGetterMapping;
import com.jenkov.db.impl.mapping.method.GetterMapping;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests the features of the GetterMapping class. So far it doesn't test
 * all of them. Some are missing, but these are implicitly tested as part
 * of other tests that use these features, so they are not untested.
 *
 * @author Jakob Jenkov, Jenkov Development
 */
public class GetterMappingTest {


    @Test
    public void testGet_Set_isAutoGenerated(){
        IGetterMapping fieldMapping = new GetterMapping();

        assertFalse(fieldMapping.isAutoGenerated(), "should default to false");

        fieldMapping.setAutoGenerated(true);
        assertTrue(fieldMapping.isAutoGenerated(), "should respond to setting it to true");

        fieldMapping.setAutoGenerated(false);
        assertFalse(fieldMapping.isAutoGenerated(), "should be false when set false");
    }

}
