package com.jenkov.db.test.mapping;

import junit.framework.TestCase;
import com.jenkov.db.itf.mapping.IGetterMapping;
import com.jenkov.db.impl.mapping.method.GetterMapping;

/**
 * Tests the features of the GetterMapping class. So far it doesn't test
 * all of them. Some are missing, but these are implicitly tested as part
 * of other tests that use these features, so they are not untested.
 *
 * @author Jakob Jenkov, Jenkov Development
 */
public class GetterMappingTest extends TestCase{

    public GetterMappingTest(String testName){
        super(testName);
    }


    public void testGet_Set_isAutoGenerated(){
        IGetterMapping fieldMapping = new GetterMapping();

        assertFalse("should default to false", fieldMapping.isAutoGenerated());

        fieldMapping.setAutoGenerated(true);
        assertTrue("should respond to setting it to true", fieldMapping.isAutoGenerated());

        fieldMapping.setAutoGenerated(false);
        assertFalse("should be false when set false", fieldMapping.isAutoGenerated());
    }

}
