DROP TABLE IF EXISTS compound_pk_objects;
CREATE TABLE compound_pk_objects(
    id          bigint,
    id2         bigint,
    name        varchar(255),

    primary key(id, id2)
);

DROP TABLE IF EXISTS persistent_object;
CREATE TABLE persistent_object (
  id            bigint,
  name          varchar,
  fieldValue    varchar,
  objectValue   varchar,
  autoColumn    timestamp,
  some_boolean  int,

  primary key (id)
);


DROP TABLE IF EXISTS other_persistent_object;
CREATE TABLE other_persistent_object (
  id            bigint,
  name          varchar,
  fieldValue    varchar,
  objectValue   varchar,
  autoColumn    timestamp,
  some_boolean  int,

  primary key (id)
);




DROP TABLE IF EXISTS ambiguous_table_name;
CREATE TABLE ambiguous_table_name (
  id        bigint,
  name      varchar(255),

  PRIMARY KEY  (id)
);


DROP TABLE IF EXISTS AmbiguousTableName;
CREATE TABLE AmbiguousTableName (
  id        bigint,
  name      varchar(255),

  PRIMARY KEY  (id)
);


DROP TABLE IF EXISTS Employees;
CREATE TABLE Employees(
  employee_id       varchar(255) NOT NULL,
  name              varchar(255) NOT NULL,
  job_title         varchar(255) NOT NULL,
  job_description   varchar(255),
  employed_since    datetime,
  monthly_salary    int,
  PRIMARY KEY (employee_id)
);


                                                                                                       
DROP TABLE IF EXISTS table1;
CREATE TABLE table1(
    id   bigint,
    text varchar(255)
);

DROP TABLE IF EXISTS table2;
CREATE TABLE table2(
    id   bigint,
    fid  bigint,
    text varchar(255)
);


DROP TABLE IF EXISTS NestedObjects;
CREATE TABLE NestedObjects (
    id bigint generated by default as identity,

    value1           varchar(255),

    nested_value_1    bigint,
    nested_value_2    varchar(255),

    nested_value_3    bigint,
    nested_value_4    varchar(255),

    primary key (id)
);


DROP TABLE IF EXISTS PrimaryObjects;
CREATE TABLE PrimaryObjects (
    id bigint generated by default as identity,

    fk_related1 bigint,

    primary key (id)
);

DROP TABLE IF EXISTS RelatedObjects1;
CREATE TABLE RelatedObjects1 (
    id bigint generated by default as identity,

    a_value varchar(255),

    primary key(id)
);

DROP TABLE IF EXISTS RelatedObjects2;
CREATE TABLE RelatedObjects2 (
    id bigint generated by default as identity,

    fk_primary bigint,

    primary key(id)
);

DROP TABLE IF EXISTS Relations;
CREATE TABLE IF EXISTS Relations(
   fk_primary bigint,
   fk_related1 bigint
);

