package com.jenkov.db.impl.mapping;

import com.jenkov.db.itf.PersistenceException;
import com.jenkov.db.itf.mapping.IObjectMapping;

import java.util.Iterator;

/**
 * @author Jakob Jenkov - Copyright 2005 Jenkov Development
 */
public class AutoGeneratedColumnsMapper extends CustomObjectMapperBase{

    protected String[] autoGeneratedColumns      = new String[0];
    protected boolean  isPrimaryKeyAutoGenerated = false;

    public AutoGeneratedColumnsMapper(String autoGeneratedColumn) {
        this.autoGeneratedColumns = new String[]{autoGeneratedColumn};
    }

    public AutoGeneratedColumnsMapper(String[] autoGeneratedColumns) {
        this.autoGeneratedColumns = autoGeneratedColumns;
    }

    public AutoGeneratedColumnsMapper(boolean isPrimaryKeyAutoGenerated) {
        this.isPrimaryKeyAutoGenerated = isPrimaryKeyAutoGenerated;
    }

    public AutoGeneratedColumnsMapper(boolean isPrimaryKeyAutoGenerated, String autoGeneratedColumn) {
        this.isPrimaryKeyAutoGenerated = isPrimaryKeyAutoGenerated;
        this.autoGeneratedColumns = new String[]{autoGeneratedColumn};
    }

    public AutoGeneratedColumnsMapper(boolean primaryKeyAutoGenerated, String[] autoGeneratedColumns) {
        this.autoGeneratedColumns = autoGeneratedColumns;
        isPrimaryKeyAutoGenerated = primaryKeyAutoGenerated;
    }

    public void modify(Object objectMappingKey, IObjectMapping mapping) throws PersistenceException {
        if(isPrimaryKeyAutoGenerated){
            for (Iterator iterator = mapping.getPrimaryKey().getColumns().iterator(); iterator.hasNext();) {
                String primaryKeyColumn = (String) iterator.next();
                mapping.getGetterMapping(primaryKeyColumn).setAutoGenerated(true);
            }
        }

        for (int i = 0; i < autoGeneratedColumns.length; i++) {
            mapping.getGetterMapping(autoGeneratedColumns[i]).setAutoGenerated(true);
        }
    }
}
